name: Compile IRBEM

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install gfortran
      run: |
         sudo apt-get install gfortran
    - name: Show gfortran version
      run: gfortran --version
    - name: Build
      shell: bash
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: |
        make OS=linux64 ENV=gfortran64 all
        make OS=linux64 ENV=gfortran64 install        
    - uses: actions/upload-artifact@v4
      with:
          name: libirbem_LINUX64_GFORTRAN64.so
          path: libirbem.so

  build-old-osx:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v4
    - name: Show gfortran version
      run: gfortran-12 --version
    - name: Build
      shell: bash
      run: |
        make OS=osx64 ENV=github all
        make OS=osx64 ENV=github install
    - uses: actions/upload-artifact@v4
      with:
          name: libirbem_MAC_OLD_MACOS64_GFORTRAN64.so
          path: libirbem.so

  build-osx:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Show gfortran version
      run: gfortran-12 --version
    - name: Build
      shell: bash
      run: |
        make OS=osx64 ENV=github all
        make OS=osx64 ENV=github install
    - uses: actions/upload-artifact@v4
      with:
          name: libirbem_MAC_M1_MACOS64_GFORTRAN64.so
          path: libirbem.so
